<?= $this->fetch('header.phtml') ?>
<!--    <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">-->
<!--        <div class="carousel-inner">-->
<!--            <div class="carousel-item active">-->
<!--                <img class="d-block w-100" src="img/ちなー.jpg" alt="slide">-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
    <div class="top-wrapper">
        <div class="container">
            <h1>茶処真壁ちなー</h1>
            <h3>築130年の古民家でくつろいでみませんか。</h3>
<!--            <div class="btn-wrapper">-->
<!--                <a href="#" class="btn signup">新規登録はこちら</a>-->
<!--                <p>or</p>-->
<!--                <a href="#" class="btn facebook"><span class="fa fa-facebook"></span>Facebookで登録</a>-->
<!--                <a href="#" class="btn twitter"><span class="fa fa-twitter"></span>Twitterで登録</a>-->
<!--            </div>-->
        </div>
    </div>
    <div class="lesson-wrapper">
        <div class="container">
            <div class="heading">
                <h2>ちなーのいいところ</h2>
            </div>
            <div class="lessons">
<!--                <div class="lesson">-->
<!--                    <div class="lesson-icon">-->
<!--                        <img src="https://prog-8.com/images/html/advanced/html.png">-->
<!--                        <p>HTML & CSS</p>-->
<!--                    </div>-->
<!--                    <p class="text-contents">ウェブページの作成に使用される言語です。HTMLとCSSを組み合わせることで、静的なページを作り上げることができます。</p>-->
<!--                </div>-->
<!--                <div class="lesson">-->
<!--                    <div class="lesson-icon">-->
<!--                        <img src="https://prog-8.com/images/html/advanced/jQuery.png">-->
<!--                        <p></p>-->
<!--                    </div>-->
<!--                    <p class="text-contents">素敵な動きを手軽に実装できるJavaScriptライブラリです。 アニメーション効果をつけたり、Ajax（エイジャックス）を使って外部ファイルを読み込んだりと色々なことができます。</p>-->
<!--                </div>-->
<!--                <div class="lesson">-->
<!--                    <div class="lesson-icon">-->
<!--                        <img src="https://prog-8.com/images/html/advanced/ruby.png">-->
<!--                        <p>Ruby</p>-->
<!--                    </div>-->
<!--                    <p class="text-contents">オープンソースの動的なプログラミング言語で、 シンプルさと高い生産性を備えています。大きなWebアプリケーションから小さな日用ツールまで、さまざまなソフトウェアを作ることができます。</p>-->
<!--                </div>-->
                <div class="card">
                    <div class="card-body">
                        <p>戦中の弾痕がお店のいたるところに。歴史を感じることができます。</p>
                    </div>
                </div>
                <div class="card">
                    <div class="card-body">
                        <p>そばの麺に合わせたあっさりしたダシが特徴です。</p>
                    </div>
                </div>
                <div class="card">
                    <div class="card-body">
                        <p>地産地消。店内で地元で採れたレタスを100円で売っています。</p>
                    </div>
                </div>
<!--                <div class="lesson">-->
<!--                    <div class="lesson-icon">-->
<!--                        <img src="https://prog-8.com/images/html/advanced/php.png">-->
<!--                        <p>PHP</p>-->
<!--                    </div>-->
<!--                    <p class="text-contents">HTMLだけではページの内容を変えることはできません。PHPはHTMLにプログラムを埋め込み、それを可能にします。</p>-->
<!--                </div>-->
                <div class="clear"></div>
            </div>
        </div>
    </div>
    <div class="message-wrapper">
        <div class="container">
            <div class="heading">
                <h2>そばを注文してみましょう！</h2><br>
                <a href="/tickets/create"><button type="button" class="btn btn-warning">注文する</button></a>
            </div>
<!--            <span class="btn message">さっそく開発する</span>-->
        </div>
    </div>
<?= $this->fetch('footer.phtml') ?>