<?= $this->fetch('header.phtml') ?>
    <div class="top-wrapper">
        <div class="container">
            <h1>茶処真壁ちなー</h1>
            <h3>築130年の古民家でくつろいでみませんか。</h3>
        </div>
    </div>
    <div class="lesson-wrapper">
        <div class="container">
            <div class="heading">
                <h2>ちなーのいいところ</h2>
            </div>
            <div class="lessons">
                <div class="card">
                    <div class="card-body">
                        <p>戦中の弾痕がお店のいたるところに。歴史を感じることができます。</p>
                    </div>
                </div>
                <div class="card">
                    <div class="card-body">
                        <p>そばの麺と相性の良いあっさりしたダシが特徴です。</p>
                    </div>
                </div>
                <div class="card">
                    <div class="card-body">
                        <p>地産地消。店内で地元で採れたレタスを100円で売っています。</p>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
    <div class="message-wrapper">
        <div class="container">
            <div class="heading">
                <h2>そばを注文する！</h2><br>
                <a href="/tickets/create"><button type="button" class="btn btn-warning">注文する</button></a>
            </div>
        </div>
    </div>
<?= $this->fetch('footer.phtml') ?>