<?= $this->fetch('header.phtml') ?>
    <form method="POST" action="/tickets">
        <div class="card">
            <div class="card-body">
                <h2 class="card-title">ブログを書く</h2>
                <div class="card-text">
                    <div class="form-group">
                        <label for="subject">タイトル</label>
                        <input type="text" name="subject" id="subject" class="form-control">
                    </div>
                </div>
            </div>
            <div class="card-body">
                <button class="btn btn-primary">投稿</button>
            </div>
        </div>
    </form>
<?= $this->fetch('footer.phtml') ?>