<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8"/>
    <title>チケット管理</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" type="text/css">
</head>
<body>
<div class="container">
    <h1>チケット管理</h1>
    <div class="card">
        <div class="card-body">
            <h2 class="card-title">チケット詳細</h2>
            <div class="card-text">
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>件名</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td><?= e($ticket['id']) ?></td>
                        <td><?= e($ticket['subject']) ?></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
</body>
</html>